### ISSUE TITLE
Need maintainer

### ISSUE THREAD

**Issue by mpharrigan** [conda-forge/fastcluster-feedstock#22]
@conda-forge/core I can no longer maintain this package, please find a new maintainer.

**Comment by beckermr** [comment]
Thanks for letting us know. If you'd like to merge a PR removing yourself, feel free. We don't have the bandwidth to actively find a maintainer, so it will likely languish until someone finds they need this package and decides to get involved.

**Comment by synapticarbors** [comment]
I'll take it over. I've added myself on the 1.2.4 PR and will try to go through and merge up to current. @mpharrigan I could leave you on as a co-maintainer in case you ever have the bandwidth

**Comment by mpharrigan** [comment]
thanks
