### ISSUE TITLE
Any plan to support osx-arm64?

### ISSUE THREAD

**Issue by isty2e** [conda-forge/fastcluster-feedstock#27]
### Comment:

It seems like this repository is no longer actively maintained (#22), but I wonder if there is any chance or plan to support osx-arm64.

**Comment by synapticarbors** [comment]
Sorry for missing this issue. I've requested that `fastcluster` be added to the migrator: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6380

**Comment by synapticarbors** [comment]
resolved by #30
